---
- name: Update, Install Docker, Git, Nmap, and Manage Docker Build Script
  hosts: ec2
  become: yes

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install Docker
      yum:
        name: docker-io
        state: latest

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Git
      yum:
        name: git
        state: latest

    - name: Install Nmap
      yum:
        name: nmap
        state: latest

    - name: Ensure the repository is present and up to date
      git:
        repo: 'https://github.com/danielitogomez/hackathon.git'
        dest: /home/ec2-user/hackathon
        version: main
        clone: yes
        update: yes
      become_user: ec2-user
      register: git_result

    - name: Execute Docker build and run script
      command: /bin/bash build-dockerfile.sh
      become_user: ec2-user
      args:
        chdir: /home/ec2-user/hackathon/build  # Ensure this is the correct path
      when: git_result.changed
